[TASK] Make shellcheck happy, streamline service output

diff --git a/.gitpod/docker/scripts/mailhog b/.gitpod/docker/scripts/mailhog
--- a/.gitpod/docker/scripts/mailhog
+++ b/.gitpod/docker/scripts/mailhog
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 ### BEGIN INIT INFO
 # Provides:
 # Required-Start:    $remote_fs $syslog
@@ -13,7 +13,7 @@ dir="/home/gitpod/"
 cmd="/home/gitpod/go/bin/MailHog"
 user="root"
 
-name=$(basename $0)
+name="MailHog"
 pid_file="/var/run/$name.pid"
 stdout_log="/var/log/$name.log"
 stderr_log="/var/log/$name.err"
@@ -23,34 +23,33 @@ get_pid() {
 }
 
 is_running() {
-    [ -f "$pid_file" ] && ps -p $(get_pid) > /dev/null 2>&1
+    [ -f "$pid_file" ] && ps -p "$(get_pid)" > /dev/null 2>&1
 }
 
 case "$1" in
     start)
     if is_running; then
-        echo "Already started"
+        echo " * $name already started"
     else
-        echo "Starting $name"
-        cd "$dir"
+        echo " * Starting $name"
+        cd "$dir" || exit
         if [ -z "$user" ]; then
-            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
+            $cmd >> "$stdout_log" 2>> "$stderr_log" &
         else
             sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
         fi
         echo $! > "$pid_file"
         if ! is_running; then
-            echo "Unable to start, see $stdout_log and $stderr_log"
+            echo " * Unable to start $name, see $stdout_log and $stderr_log"
             exit 1
         fi
     fi
     ;;
     stop)
     if is_running; then
-        echo -n "Stopping $name.."
-        kill `get_pid`
+        echo -n " * Stopping $name"
+        kill "$(get_pid)"
         for i in 1 2 3 4 5 6 7 8 9 10
-        # for i in `seq 10`
         do
             if ! is_running; then
                 break
@@ -62,31 +61,31 @@ case "$1" in
         echo
 
         if is_running; then
-            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            echo " * $name not stopped; may still be shutting down or shutdown may have failed"
             exit 1
         else
-            echo "Stopped"
+            echo " * $name stopped"
             if [ -f "$pid_file" ]; then
                 rm "$pid_file"
             fi
         fi
     else
-        echo "Not running"
+        echo " * $name not running"
     fi
     ;;
     restart)
     $0 stop
     if is_running; then
-        echo "Unable to stop, will not attempt to start"
+        echo " * Unable to stop $name, will not attempt to start"
         exit 1
     fi
     $0 start
     ;;
     status)
     if is_running; then
-        echo "Running"
+        echo " * $name running"
     else
-        echo "Stopped"
+        echo " * $name stopped"
         exit 1
     fi
     ;;
